version: 2
updates:
  - package-ecosystem: npm
    directory: /web/app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      web-client-production:
        dependency-type: production
      web-client-development:
        dependency-type: development

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      mobile-production:
        dependency-type: production
      mobile-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
